# Grafana Datasource Provisioning
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated.monitoring.svc.cluster.local:9090
    uid: prometheus-uid
    isDefault: true
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo-uid
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki.monitoring.svc.cluster.local:3100
    uid: loki-uid
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: tempo-uid
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo.monitoring.svc.cluster.local:3200
    uid: tempo-uid
    jsonData:
      tracesToLogs:
        datasourceUid: loki-uid
        tags: [job, namespace]
      serviceMap:
        datasourceUid: prometheus-uid
      nodeGraph:
        enabled: true
    editable: false
